### ISSUE TITLE
Strings in Tex-Tabelle schreiben

### ISSUE THREAD

**Issue by anjabeck** [DimensionalScoop/kautschuk#1]
Es wäre manchmal echt nützlich, wenn man mit make_table (aus dem Skript, das Tex-Code produziert) auch Strings in eine Tabelle schreiben könnte.

**Comment by DerKleineGauss** [comment]
Danke für deine Anfrage! Dies erscheint mir ebenfalls sinnvoll, sodass bei Zeiten sich hoffentlich jemand darum kümmern wird :)

**Comment by DerKleineGauss** [comment]
Soo, das von dir angedachte Verhalten von make_table ist jetzt implementiert. Das heißt ihr könnt jetzt listen von strings mit make_table in Tabellen bringen. zB
list = ["string_one", "string_two"]
make_table(list)
Wichtig ist: 
wenn anschließend make_full_table verwendet werden soll (was auch funktioniert wenn die folgenden Bedingungen erfüllt sind), so beachtet:
- der String darf folgendes nicht enthalten : << . & \ 1 2 3 4 5 6 7 8 9 0 >>
